serverFiles:
# Insert the correct values in all parameters marked with "#TODO"
  alerting_rules.yml:
      groups:
      - name: NodeDown
        rules:
        # Alert for any instance that is unreachable for >5 minutes.
        - alert: InstanceDown
          expr: up{job="kubernetes-nodes"} == 0
          for: 2m
          labels:
            severity: page
          annotations:
            host: "{{ $labels.kubernetes_io_hostname }}"
            summary: "Instance down"
            description: "Node {{ $labels.kubernetes_io_hostname }} has been down for more than 5 minutes."
      - name: low_memory_alert
        rules:
        - alert: LowMemory
          expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 85
          for: 2m
          labels:
            severity: warning
          annotations:
            host: "{{ $labels.kubernetes_node }}"
            summary: "{{ $labels.kubernetes_node }} Host is low on memory. Only {{ $value }}% left."
            description: "{{ $labels.kubernetes_node }} node is low on memory. Only {{ $value }}% left."
        - alert: KubePersistentVolumeErrors
          expr: #TODO
          for: 2m
          labels:
            severity: critical
          annotations:
            description: #TODO
            summary: PersistentVolume is having issues with provisioning.
        - alert: KubePodCrashLooping
          expr: #TODO
          for: 2m
          labels:
            severity: warning
          annotations:
            description: #TODO
            summary: Pod is crash looping.
        - alert: KubePodNotReady
          expr: #TODO
          for: 2m
          labels:
            severity: warning
          annotations:
            description: #TODO
            summary: Pod has been in a non-ready state for more than 2 minutes.
